=== Pf2eToolsOrg/Pf2eTools/test/schema/items-base.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"version": "1.4.2",
	"definitions": {
		"itemLookup": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"abbreviation": {
						"type": "string"
					},
					"source": {
						"type": "string"
					},
					"page": {
						"type": "integer"
					},
					"name": {
						"type": "string"
					},
					"entries": {
						"type": "array",
						"items": {
							"$ref": "entry.json"
						}
					},
					"template": {
						"$comment": "Note that this is not used on item types.",
						"type": "string"
					}
				},
				"required": [
					"abbreviation",
					"source",
					"page"
				],
				"additionalProperties": false
			}
		}
	},
	"type": "object",
	"properties": {
		"baseitem": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"type": {
						"type": "string"
					},
					"rarity": {
						"type": "string",
						"description": "\"None\" is for mundane items. \"Unknown (Magic)\" is for miscellaneous magical items. \"Unknown\" is for miscellaneous mundane items.",
						"enum": [
							"rare",
							"none",
							"uncommon",
							"very rare",
							"legendary",
							"artifact",
							"unknown",
							"common",
							"unknown (magic)"
						]
					},
					"source": {
						"type": "string"
					},
					"page": {
						"type": "integer"
					},
					"ac": {
						"type": "integer"
					},
					"age": {
						"type": "string"
					},
					"armor": {
						"description": "Flag used when merging generic variants",
						"type": "boolean"
					},
					"axe": {
						"type": "boolean"
					},
					"dmg1": {
						"type": "string"
					},
					"dmg2": {
						"type": "string"
					},
					"dmgType": {
						"type": "string"
					},
					"entries": {
						"type": "array",
						"items": {
							"$ref": "entry.json"
						}
					},
					"property": {
						"type": "array",
						"items": {
							"type": "string",
							"enum": ["T", "V", "H", "2H", "F", "L", "R", "A", "LD", "S", "AF", "RLD", "BF"]
						}
					},
					"range": {
						"type": "string"
					},
					"reload": {
						"type": "integer"
					},
					"scfType": {
						"type": "string"
					},
					"stealth": {
						"type": "boolean"
					},
					"strength": {
						"type": "string"
					},
					"sword": {
						"type": "boolean"
					},
					"mace": {
						"type": "boolean"
					},
					"spear": {
						"type": "boolean"
					},
					"hammer": {
						"type": "boolean"
					},
					"bow": {
						"type": "boolean"
					},
					"crossbow": {
						"type": "boolean"
					},
					"club": {
						"type": "boolean"
					},
					"dagger": {
						"type": "boolean"
					},
					"net": {
						"type": "boolean"
					},
					"firearm": {
						"type": "boolean"
					},
					"staff": {
						"description": "Adds the italicized \"Staff\" text to the item info line (below the name).",
						"type": "boolean"
					},
					"value": {
						"description": "In copper pieces.",
						"type": "number"
					},
					"currencyConversion": {
						"description": "ID of a value conversion table. Homebrew only.",
						"type": "string"
					},
					"valueMult": {
						"type": "number"
					},
					"weapon": {
						"type": "boolean"
					},
					"weaponCategory": {
						"type": "string"
					},
					"weight": {
						"type": "number"
					},
					"weightMult": {
						"type": "number"
					},
					"quantity": {
						"type": "integer"
					},
					"srd": {
						"$ref": "util.json#/definitions/srd"
					},
					"otherSources": {
						"$ref": "util.json#/definitions/otherSources"
					},
					"ammoType": {
						"type": "string"
					},
					"packContents": {
						"type": "array",
						"items": {
							"oneOf": [
								{
									"type": "string"
								},
								{
									"type": "object",
									"properties": {
										"special": {
											"type": "string"
										},
										"quantity": {
											"type": "integer"
										}
									},
									"additionalProperties": false,
									"required": ["special"]
								},
								{
									"type": "object",
									"properties": {
										"item": {
											"type": "string"
										},
										"quantity": {
											"type": "integer"
										}
									},
									"additionalProperties": false,
									"required": ["item", "quantity"]
								}
							]
						}
					}
				},
				"required": [
					"name",
					"type",
					"rarity",
					"source",
					"page"
				],
				"additionalProperties": false
			}
		},
		"itemProperty": {
			"$ref": "#/definitions/itemLookup"
		},
		"itemType": {
			"$ref": "#/definitions/itemLookup"
		},
		"itemTypeAdditionalEntries": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"appliesTo": {
						"type": "string"
					},
					"entries": {
						"type": "array",
						"items": {
							"$ref": "entry.json"
						}
					}
				},
				"additionalProperties": false
			}
		}
	},
	"additionalProperties": false
}

=== Pf2eToolsOrg/Pf2eTools/data/items-base.json
{
	"baseitem": [
		{
			"name": "Antimatter Rifle",
			"source": "DMG",
			"page": 268,
			"type": "R",
			"rarity": "none",
			"weight": 10,
			"weaponCategory": "martial",
			"age": "futuristic",
			"property": [
				"AF",
				"RLD",
				"2H"
			],
			"range": "120/360",
			"reload": 2,
			"dmg1": "6d8",
			"dmgType": "N",
			"firearm": true,
			"weapon": true,
			"ammoType": "energy cell"
		},
		{
			"name": "Arrow",
			"source": "PHB",
			"page": 150,
			"srd": true,
			"type": "A",
			"rarity": "none",
			"weight": 0.05,
			"value": 5
		},
		{
			"name": "Arrows (20)",
			"source": "PHB",
			"page": 150,
			"srd": true,
			"type": "A",
			"rarity": "none",
			"weight": 1,
			"value": 100,
			"packContents": [
				{
					"item": "arrow|phb",
					"quantity": 20
				}
			]
		},
		{
			"name": "Automatic Pistol",
			"source": "DMG",
			"page": 268,
			"type": "R",
			"rarity": "none",
			"weight": 3,
			"weaponCategory": "martial",
			"age": "modern",
			"property": [
				"AF",
				"RLD"
			],
			"range": "50/150",
			"reload": 15,
			"dmg1": "2d6",
			"dmgType": "P",
			"firearm": true,
			"weapon": true,
			"ammoType": "modern bullet"
		},
		{
			"name": "Automatic Rifle",
			"source": "DMG",
			"page": 268,
			"type": "R",
			"rarity": "none",
			"weight": 8,
			"weaponCategory": "martial",
			"age": "modern",
			"property": [
				"AF",
				"BF",
				"RLD",
				"2H"
			],
			"range": "80/240",
			"reload": 30,
			"dmg1": "2d8",
			"dmgType": "P",
			"firearm": true,
			"weapon": true,
			"ammoType": "modern bullet"
		},
		{
			"name": "Battleaxe",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 4,
			"value": 1000,
			"weaponCategory": "martial",
			"property": [
				"V"
			],
			"dmg1": "1d8",
			"dmgType": "S",
			"dmg2": "1d10",
			"axe": true,
			"weapon": true
		},
		{
			"name": "Blowgun",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "R",
			"rarity": "none",
			"weight": 1,
			"value": 1000,
			"weaponCategory": "martial",
			"property": [
				"A",
				"LD"
			],
			"range": "25/100",
			"dmg1": "1",
			"dmgType": "P",
			"weapon": true,
			"ammoType": "blowgun needle|phb"
		},
		{
			"name": "Blowgun Needle",
			"source": "PHB",
			"page": 150,
			"srd": true,
			"type": "A",
			"rarity": "none",
			"weight": 0.02,
			"value": 2
		},
		{
			"name": "Blowgun Needles (50)",
			"source": "PHB",
			"page": 150,
			"srd": true,
			"type": "A",
			"rarity": "none",
			"weight": 1,
			"value": 100,
			"packContents": [
				{
					"item": "blowgun needle|phb",
					"quantity": 50
				}
			]
		},
		{
			"name": "Breastplate",
			"source": "PHB",
			"page": 145,
			"srd": true,
			"type": "MA",
			"rarity": "none",
			"weight": 20,
			"value": 40000,
			"ac": 14,
			"armor": true,
			"entries": [
				"This armor consists of a fitted metal chest piece worn with supple leather. Although it leaves the legs and arms relatively unprotected, this armor provides good protection for the wearer's vital organs while leaving the wearer relatively unencumbered."
			]
		},
		{
			"name": "Chain Mail",
			"source": "PHB",
			"page": 145,
			"srd": true,
			"type": "HA",
			"rarity": "none",
			"weight": 55,
			"value": 7500,
			"ac": 16,
			"strength": "13",
			"armor": true,
			"stealth": true,
			"entries": [
				"Made of interlocking metal rings, chain mail includes a layer of quilted fabric worn underneath the mail to prevent chafing and to cushion the impact of blows. The suit includes gauntlets."
			]
		},
		{
			"name": "Chain Shirt",
			"source": "PHB",
			"page": 144,
			"srd": true,
			"type": "MA",
			"rarity": "none",
			"weight": 20,
			"value": 5000,
			"ac": 13,
			"armor": true,
			"entries": [
				"Made of interlocking metal rings, a chain shirt is worn between layers of clothing or leather. This armor offers modest protection to the wearer's upper body and allows the sound of the rings rubbing against one another to be muffled by outer layers."
			]
		},
		{
			"name": "Club",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 2,
			"value": 10,
			"weaponCategory": "simple",
			"property": [
				"L"
			],
			"dmg1": "1d4",
			"dmgType": "B",
			"club": true,
			"weapon": true
		},
		{
			"name": "Crossbow Bolt",
			"source": "PHB",
			"page": 150,
			"srd": true,
			"type": "A",
			"rarity": "none",
			"weight": 0.075,
			"value": 5
		},
		{
			"name": "Crossbow Bolts (20)",
			"source": "PHB",
			"page": 150,
			"srd": true,
			"type": "A",
			"rarity": "none",
			"weight": 1.5,
			"value": 100,
			"packContents": [
				{
					"item": "crossbow bolt|phb",
					"quantity": 20
				}
			]
		},
		{
			"name": "Crystal",
			"source": "PHB",
			"page": 151,
			"srd": true,
			"type": "SCF",
			"scfType": "arcane",
			"rarity": "none",
			"weight": 1,
			"value": 1000
		},
		{
			"name": "Dagger",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 1,
			"value": 200,
			"weaponCategory": "simple",
			"property": [
				"F",
				"L",
				"T"
			],
			"range": "20/60",
			"dmg1": "1d4",
			"dmgType": "P",
			"dagger": true,
			"weapon": true
		},
		{
			"name": "Dart",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "R",
			"rarity": "none",
			"weight": 0.25,
			"value": 5,
			"weaponCategory": "simple",
			"property": [
				"F",
				"T"
			],
			"range": "20/60",
			"dmg1": "1d4",
			"dmgType": "P",
			"weapon": true
		},
		{
			"name": "Double-Bladed Scimitar",
			"source": "ERLW",
			"page": 21,
			"otherSources": [
				{
					"source": "UAWGE",
					"page": 74
				}
			],
			"type": "M",
			"rarity": "none",
			"weight": 6,
			"value": 10000,
			"weaponCategory": "martial",
			"property": [
				"S",
				"2H"
			],
			"dmg1": "2d4",
			"dmgType": "S",
			"sword": true,
			"weapon": true,
			"entries": [
				{
					"type": "entries",
					"name": "Special",
					"entries": [
						"If you attack with a double-bladed scimitar as part of the {@action Attack} action on your turn, you can use a bonus action immediately after to make a melee attack with it. This attack deals {@dice 1d4} slashing damage on a hit, instead of {@dice 2d4}."
					]
				}
			]
		},
		{
			"name": "Energy Cell",
			"source": "DMG",
			"page": 268,
			"type": "AF",
			"rarity": "none",
			"weight": 0.3125,
			"age": "futuristic"
		},
		{
			"name": "Flail",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 2,
			"value": 1000,
			"weaponCategory": "martial",
			"dmg1": "1d8",
			"dmgType": "B",
			"weapon": true
		},
		{
			"name": "Glaive",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 6,
			"value": 2000,
			"weaponCategory": "martial",
			"property": [
				"H",
				"R",
				"2H"
			],
			"dmg1": "1d10",
			"dmgType": "S",
			"weapon": true
		},
		{
			"name": "Greataxe",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 7,
			"value": 3000,
			"weaponCategory": "martial",
			"property": [
				"H",
				"2H"
			],
			"dmg1": "1d12",
			"dmgType": "S",
			"axe": true,
			"weapon": true
		},
		{
			"name": "Greatclub",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 10,
			"value": 20,
			"weaponCategory": "simple",
			"property": [
				"2H"
			],
			"dmg1": "1d8",
			"dmgType": "B",
			"club": true,
			"weapon": true
		},
		{
			"name": "Greatsword",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 6,
			"value": 5000,
			"weaponCategory": "martial",
			"property": [
				"H",
				"2H"
			],
			"dmg1": "2d6",
			"dmgType": "S",
			"sword": true,
			"weapon": true
		},
		{
			"name": "Halberd",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 6,
			"value": 2000,
			"weaponCategory": "martial",
			"property": [
				"H",
				"R",
				"2H"
			],
			"dmg1": "1d10",
			"dmgType": "S",
			"weapon": true
		},
		{
			"name": "Half Plate Armor",
			"source": "PHB",
			"page": 145,
			"srd": true,
			"type": "MA",
			"rarity": "none",
			"weight": 40,
			"value": 75000,
			"ac": 15,
			"armor": true,
			"stealth": true,
			"entries": [
				"Half plate consists of shaped metal plates that cover most of the wearer's body. It does not include leg protection beyond simple greaves that are attached with leather straps."
			]
		},
		{
			"name": "Hand Crossbow",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "R",
			"rarity": "none",
			"weight": 3,
			"value": 7500,
			"weaponCategory": "martial",
			"property": [
				"A",
				"L",
				"LD"
			],
			"range": "30/120",
			"dmg1": "1d6",
			"dmgType": "P",
			"crossbow": true,
			"weapon": true,
			"ammoType": "crossbow bolt|phb"
		},
		{
			"name": "Handaxe",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "M",
			"rarity": "none",
			"weight": 2,
			"value": 500,
			"weaponCategory": "simple",
			"property": [
				"L",
				"T"
			],
			"range": "20/60",
			"dmg1": "1d6",
			"dmgType": "S",
			"axe": true,
			"weapon": true
		},
		{
			"name": "Heavy Crossbow",
			"source": "PHB",
			"page": 149,
			"srd": true,
			"type": "R",
			"rarity": "none",
			"weight": 18,
			"value": 5000,
			"weaponCategory": "martial",
			"property": [
				"A",
				"H",
				"LD",
				"2H"
			],
			"range": "100/400",
			"dmg1": "1d10",
			"dmgType": "P",
			"crossbow": true,
			"weapon": true,
			"ammoType": "crossbow bolt|phb"
		},
		{
			"name": "Hide Armor",
			"source": "PHB",
			"page": 144,
			"srd": true,
			"type": "MA",
			"rarity": "none",
			"weight": 12,
			"value": 1000,
			"ac": 12,
			"armor": true,
			"entries": [
